# Warning: This file is generated automatically, and should not be modified.
# Instead, please modify the template in the pr-checks directory and run:
#     pr-checks/sync.sh
# to regenerate this file.

name: PR Check - Swift analysis using a custom build command
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
on:
  push:
    branches:
      - main
      - releases/v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch: {}
  workflow_call: {}
jobs:
  swift-custom-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            version: linked
          - os: macos-latest
            version: default
          - os: macos-latest
            version: nightly-latest
    name: Swift analysis using a custom build command
    permissions:
      contents: read
      security-events: read
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Prepare test
        id: prepare-test
        uses: ./.github/actions/prepare-test
        with:
          version: ${{ matrix.version }}
          use-all-platform-bundle: 'false'
          setup-kotlin: 'true'
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.0'
          cache: false
      - uses: ./../action/init
        id: init
        with:
          languages: swift
          tools: ${{ steps.prepare-test.outputs.tools-url }}
      - uses: ./../action/.github/actions/setup-swift
        with:
          codeql-path: ${{steps.init.outputs.codeql-path}}
      - name: Check working directory
        shell: bash
        run: pwd
      - name: Build code
        shell: bash
        run: ./build.sh
      - uses: ./../action/analyze
        id: analysis
        with:
          upload-database: false
      - name: Check database
        shell: bash
        run: |
          SWIFT_DB="${{ fromJson(steps.analysis.outputs.db-locations).swift }}"
          if [[ ! -d "$SWIFT_DB" ]]; then
            echo "Did not create a database for Swift."
            exit 1
          fi
    env:
      DOTNET_GENERATE_ASPNET_CERTIFICATE: 'false'
      CODEQL_ACTION_TEST_MODE: true
